### ISSUE TITLE
GridDB fails to start on Ubuntu 23&24 with systemctl

### ISSUE THREAD

**Issue by Imisrael** [griddb/griddb#456]
When I attempt to start GridDB on a newer version of Ubuntu, 24 in my case, it fails due to a python error.

First, here is my env: 

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
```

After installing GridDB v5.5, I try to start and I get this error: 

```
$ sudo systemctl start gridstore

Job for gridstore.service failed because the control process exited with error code.
See "systemctl status gridstore.service" and "journalctl -xeu gridstore.service" for details.
```

And reading the journalctl: 

```
May 16 17:10:59 griddb-server gridstore[3078]: Starting gridstore service:
May 16 17:11:02 griddb-server gridstore[3093]: Traceback (most recent call last):
May 16 17:11:02 griddb-server gridstore[3093]:   File "/usr/bin/gs_startnode", line 133, in <module>
May 16 17:11:02 griddb-server gridstore[3093]:     serverPid = util.getpid(pidfile)
May 16 17:11:02 griddb-server gridstore[3093]:                 ^^^^^^^^^^^^^^^^^^^^
May 16 17:11:02 griddb-server gridstore[3093]:   File "/usr/griddb-5.5.0/bin/util.py", line 191, in getpid
May 16 17:11:02 griddb-server gridstore[3093]:     fp = open(path, 'rU')
May 16 17:11:02 griddb-server gridstore[3093]:          ^^^^^^^^^^^^^^^^
May 16 17:11:02 griddb-server gridstore[3093]: ValueError: invalid mode: 'rU'
May 16 17:11:02 griddb-server gridstore[3078]: Stopping gridstore service:
May 16 17:11:02 griddb-server gridstore[3148]: A80101: The node has not been joined to the GridDB cluster.
May 16 17:11:04 griddb-server gridstore[3078]: Stopped.
May 16 17:11:04 griddb-server gridstore[3078]: F01002: Startnode error
May 16 17:11:04 griddb-server gridstore[3078]: [ FAILED ]
```

According to python docs, the `U` option is now deprecated for `open`, so simply removing this seems to allow GridDB to run like normal.

**Comment by knonomura** [comment]
Thank you for your report for Ubuntu24.
I'll confirm it.

**Comment by xumoyunerkinov** [comment]
thank you
